### ISSUE TITLE
Add support for merging Reactive Logger MDC with standard MDC

### ISSUE THREAD

**Issue by Michal-Kucera** [Numichi/reactive-logger#8]
Hi @Numichi,

I saw a comment at https://youtrack.jetbrains.com/issue/KT-50805, which inspired me to solve my issue with Spring Cloud Sleuth OTEL (more details [here](https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/issues/122)) by using your library, thanks for developing it!

The main problem is that if I use basic logger without your MDC context, I have `traceId` and `spanId`, but I do not have `userId`. On the other side, if I use your MDC context, I have only `userId`, but no `traceId` nor `spanId`.

The workaround I found is to set `userId` in your MDC context and then just get `userId` from there and paste it to the current MDC context just before I produce a log record. I'm wondering if there could be an easier way to merge MDC context from your library with the current MDC context, rather than what I have developed as a workaround ([see the code here](https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/issues/122#issuecomment-1231497795)).

One of the solution that crossed my mind is to implement a wrapper for KLogger interface, which would do exactly what my KLogger extension does - read your MDC and add values from it to the current MDC.

WDYT?

Cheers,
Michal

**Comment by Numichi** [comment]
Thanks for the comment, I'll check it out tonight (GMT+2) and I will answer here.

**Comment by Numichi** [comment]
Please correct me, If I say anything wrong or I misunderstood your question.

In contrast to the Tomcat world, threads are mostly fixed in the reactive environment with Netty. So we have a thread pool, so if any process waits for anything it will be suspended, and another process can use it. 

See: https://stackoverflow.com/questions/46925508/default-number-of-threads-in-spring-boot-2-0-reactive-webflux-configuration

So more processes can use the same thread. So, the thread stores the well-known MDC. So, when another process is activated, it can overwrite the ThreadLocal data. I don't trust that. _This is what you do when you call MDC.put() in "Extension for KLogger"._

I think It is safer if all data travels in the reactive context _like your code in filter_. If you configure a simple "Spring Cloud Sleuth" you can see that it puts some information in the ReactorContext. So if we preload the MDC stored in the ThreadLocal, but it is used later, it might cause a problem later depending on some running context, but not always. _In your code similar, you prelead slf4j MDC before and logging._ Therefore, this library takes a snapshot of the data selected from reactive context, which it transfers to the ThreadLocal, does logging and clears slf4j's MDC content so as not to interfere with other processes. See `io.github.numichi.reactive.logger.reactor.MDCSnapshot#close` and `MDCSnapshot : AutoCloseable`.

Reference: https://projectreactor.io/docs/core/release/reference/#faq.mdc

Since I also had a problem with "Spring Cloud Sleuth" because I needed traceId and spanId, I came up with the idea of making a global solution for this. This is my hook idea what I would like to release on v3. The main concept is that the reactor context can be given any type, but MDC is String-based. So it is necessary to transform.

---

My MDC is nothing more than a map that travels in the reactor context and is similar type (Map<String, String>) to slf4j's map. In the background, my MDC will be injected into the MDC of slf4j.

`io.github.numichi.reactive.logger.ICore#takeMDCSnapshot` what call `io.github.numichi.reactive.logger.reactor.MDCSnapshot#of` and used `org.slf4j.MDC.setContextMap(mapStringStringFromMyMDC)` on every logging trigger. Library core module: `io.github.numichi.reactive.logger.reactor.IReactorCore#wrap`

So, try it:

```kotlin
class AnyName {
    val logger = CoroutineLogger.reactorBuilder().setLogger(org.slf4j.LoggerFactory.getLogger(AnyName::class.java)).build()
    val logger2 = ReactiveLogger.builder().setLogger(org.slf4j.LoggerFactory.getLogger(AnyName::class.java)).build()

    suspend fun yourMethod() {
        val mdc = readMdc()
        mdc["a"] = "b"
        withMDCContext(mdc) {
            logger.info("message") // slf4j MDC will store {"a": "b"}
        }
    }

    fun yourMethodMono(): Mono<Void> {
        return Mono.just(1)
            .flatMap {
                logger2.info("message") // slf4j MDC will store {"a": "b"}
            }
            .contextWrite { 
                MDCContext.modifyContext(it) { mdc ->
                    mdc["a"] = "b"
                }
            }
            .then()
    }
}
```

**Comment by Michal-Kucera** [comment]
Yes, I believe you understood my query well.

If I got your point with attached snippet correctly, if we built our logger with `CoroutineLogger#reactorBuilder()` or even `CoroutineLogger#builder()`, it should keep reactive-MDC updated with values from non-reactive MDC, right? Thus `spanId` and `traceId` produced by Spring Sleuth will be available when I use reactive-MDC when calling logger. (I will try this out first thing tomorrow morning)

Though, my main point was to not need this step of building reactive logger, and using reactive-MDC when logging at all, or at least reduce the custom code required. Instead, use standard loggers as they are - I suppose v3 with hooks shall solve this, happy to see it in action any soon!

On the other side - is the issue with my current "workaround" that it doesn't clean `userId` from non-reactive MDC after logging a message?

Thanks!
Michal

**Comment by Numichi** [comment]
### If I got your point with attached snippet correctly, if we built our logger with CoroutineLogger#reactorBuilder() or even CoroutineLogger#builder(), it should keep reactive-MDC updated with values from non-reactive MDC, right?

Yes. Just MDC will be clear after logging.

Side note: `reactorBuilder` is an alias, and you don't need to specify where the data comes from because the source is the same for ReactorContext.

```kotlin
typealias CCKey<E> = CoroutineContext.Key<E>
typealias CCResolveFn<E> = suspend (CCKey<out E>) -> ContextView?

// io.github.numichi.reactive.logger.coroutine.CoroutineLogger
companion object {
    @JvmStatic
    fun <E : CoroutineContext.Element> builder(element: CCKey<E>, contextExtractive: CCResolveFn<E>): Builder<E> {
        return Builder(element, contextExtractive)
    }

    @JvmStatic
    fun reactorBuilder(): Builder<ReactorContext> {
        return builder(ReactorContext) { coroutineContext[it]?.context }
    }
}
```
---
### at least reduce the custom code required. Instead, use standard loggers as they are

I totally understand your point. I uploaded this on GitHub because I didn't want to bring it into my projects. And if someone else encounters this problem, let's share the knowledge. :)

This lib is not a custom logger library. Just a layer on slf4j for support reactive environment. Not more. In the background, it calls slf4j logger in the same way, just wrapped in an MDC inject-clear mechanism. So you can use logback or log4j implementation dependency.

---
### I suppose v3 with hooks shall solve this, happy to see it in action any soon!

It is already in the final review, if I don't find any problems with it, I will release it. :)

---
### On the other side - is the issue with my current "workaround" that it doesn't clean userId from non-reactive MDC after logging a message?

It doesn't clear because you modify MDC directly. According to C.7 of documentation of ReactorProject used Closeable type. It takes the data out of context and passes it to MDC and creates a "remover" that triggers when leaving the try scope, it activates the close method by the Closeable interface.

```java
//...
Optional<String> toPutInMdc = signal.getContext().getOrEmpty("CONTEXT_KEY"); 
toPutInMdc.ifPresentOrElse(tpim -> {
    try (MDC.MDCCloseable cMdc = MDC.putCloseable("MDC_KEY", tpim)) { 
        logStatement.accept(signal.get()); 
    }
},
//...

// in org.slf4j.MDC
public static MDCCloseable putCloseable(String key, String val) throws IllegalArgumentException {
    put(key, val);
    return new MDCCloseable(key);
}

public class MDC {
    // ...
    public static class MDCCloseable implements Closeable {
        private final String key;

        private MDCCloseable(String key) {
            this.key = key;
        }

        public void close() {
            MDC.remove(this.key);
        }
    }
}
```

**Comment by Numichi** [comment]
I would publish it if the repository manager would let it... About still 30 mins in "closing operation" on the open stage. It is average time about 3-5 mins, not 30 mins. 🗡️

**Comment by Numichi** [comment]
`3.0.0-RC1` has been released and you can download via maven or gradle. Not `3.0.0` because I haven't tried it in my project yet, just a minimal test code. You can try this.

_The mvnrepository.com need 1-2 days to appear new version but don't let that bother you. If you can see version [here](https://repo1.maven.org/maven2/io/github/numichi/reactive-logger/) you can reach it._

I use a log4j2 plugin for JSON log format here and my test:

```kotlin
package com.example.webfluxsluashlogtest

import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import org.apache.logging.log4j.core.Appender
import org.apache.logging.log4j.core.LogEvent
import org.apache.logging.log4j.core.config.Node
import org.apache.logging.log4j.core.config.plugins.Plugin
import org.apache.logging.log4j.core.config.plugins.PluginFactory
import org.apache.logging.log4j.core.layout.AbstractStringLayout
import java.nio.charset.Charset

@Plugin(name = "ExamplePlugin", category = Node.CATEGORY, elementType = Appender.ELEMENT_TYPE)
class ExamplePlugin : AbstractStringLayout(Charset.defaultCharset()) {
    companion object {

        @JvmStatic
        @PluginFactory
        fun pluginFactory() = ExamplePlugin()
    }

    private val mapper = jacksonObjectMapper().registerModule(JavaTimeModule())

    override fun toSerializable(event: LogEvent): String {
        val model = LogModel(
            event.message.formattedMessage,
            event.contextData.toMap()
        )

        return mapper.writeValueAsString(model) + "\n"
    }
}

data class LogModel(
    val message: String,
    val context: Map<String, String>
)
```
```xml
<!-- src/main/resources/log4j2.xml -->
<Configuration packages="com.example.webfluxsluashlogtest">
    <Appenders>
        <Console name="ExampleLog">
            <ExamplePlugin/>
        </Console>
    </Appenders>

    <Loggers>
        <AsyncRoot level="info">
            <AppenderRef ref="ExampleLog"/>
        </AsyncRoot>
    </Loggers>
</Configuration>
```
```kotlin
package com.example.webfluxsluashlogtest

import io.github.numichi.reactive.logger.Configuration
import io.github.numichi.reactive.logger.LoggerFactory.getKLogger
import io.github.numichi.reactive.logger.coroutine.CoroutineLogger
import kotlinx.coroutines.reactor.ReactorContext
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.cloud.sleuth.TraceContext
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RestController
import kotlin.coroutines.coroutineContext

@SpringBootApplication
class WebfluxSluashLogTestApplication

fun main(args: Array<String>) {

    Configuration.addGenericHook<TraceContext>(
        hookName = "xxx",
        contextKey = org.springframework.cloud.sleuth.TraceContext::class.java,
        hook = { it, _ ->
            mapOf(
                "traceId" to "${it?.traceId()}",
                "parentId" to (it?.parentId() ?: ""),
                "spanId" to "${it?.spanId()}"
            )
        }
    )

    runApplication<WebfluxSluashLogTestApplication>(*args)
}

@RestController
class EndPointController {

    val loggerK = CoroutineLogger.reactorBuilder().setLogger(getKLogger(this::class.java)).build()

    @GetMapping
    suspend fun asdfasdfasdfasdfasdf() {
        val x = coroutineContext[ReactorContext]?.context?.get(org.springframework.cloud.sleuth.TraceContext::class.java)
        println(x?.spanId())
        println(x?.traceId())

        loggerK.info("foo")
    }
}
```

Log:
```
{"message":"No active profile set, falling back to 1 default profile: \"default\"","context":{}}
{"message":"BeanFactory id=42d9e07a-adee-3fb4-9b01-1fdab50f02f0","context":{}}
{"message":"Cannot determine local hostname","context":{}}
{"message":"Exposing 1 endpoint(s) beneath base path '/actuator'","context":{}}
{"message":"Cannot determine local hostname","context":{}}
{"message":"Netty started on port 8080","context":{}}
{"message":"Cannot determine local hostname","context":{}}
{"message":"Cannot determine local hostname","context":{}}
{"message":"Started WebfluxSluashLogTestApplicationKt in 7.548 seconds (JVM running for 8.482)","context":{}}
b05c8393a3eeabb4
b05c8393a3eeabb4
{"message":"foo","context":{"spanId":"b05c8393a3eeabb4","traceId":"b05c8393a3eeabb4","parentId":""}}
```

**Comment by Michal-Kucera** [comment]
Hey @Numichi !

Got a little bit of delay over here, yet, `3.0.0-RC1` appears to be working undoubtedly well, thanks a lot mate!!

I'm attaching a screenshot from my tests (see `traceId`, `spanId` and `userId` fields being logged correctly).

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/46457233/188977989-e39d10c3-9385-479d-9292-f6d152b29264.png">

**A thought to think of:**

I've created a configuration class which does the aforementioned, might be something to include into this library in Spring auto-configuration style manner (if you apply some fine-tunning):

```kotlin
package com.payxpert.transaction.configuration.logger

import io.github.numichi.reactive.logger.Configuration.addGenericHook
import io.github.numichi.reactive.logger.MDC
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass
import org.springframework.cloud.sleuth.TraceContext
import org.springframework.context.annotation.Configuration
import javax.annotation.PostConstruct

@Configuration
@ConditionalOnClass(TraceContext::class)
class ReactiveLoggerAutoconfiguration {

    @PostConstruct
    fun addLoggerHookForTraceContext() = addGenericHook<TraceContext>(
        hookName = "${MDC::class.simpleName}",
        contextKey = TraceContext::class.java,
        hook = { traceContext, _ ->
            mapOf(
                "traceId" to "${traceContext?.traceId()}",
                "parentId" to (traceContext?.parentId() ?: ""),
                "spanId" to "${traceContext?.spanId()}"
            )
        }
    )
}
```

**Comment by Numichi** [comment]
- Thanks for the feedback, I'll investigate the delay.

- I was also thinking about a Spring Boot compatibility automatic configuration that can be configured by properties, just it can be very special. See hook customization algorithm.

- `logger {}` optional comes from the KLogger library `io.github.microutils:kotlin-logging-jvm:2.1.23` To work with this, CoroutineKLogger is for that. If you want an slf4j logger, CoroutineLogger. :)

**Comment by Numichi** [comment]
I have investigated this delay issue. I have not found relevant problems in the code. Can you give me a description what kind of your infrastructure is? If you use ElasticSearch or external storage there is some delay while the data will be stored. 
My test score is between the logger object and log4j2 and test environment is my local machine. There was a slow element when calling first logger method that created cache. It was about 13ms. After, every logging was below 1ms. I resolved this first slowest issue.

Another topic, I want to reference your previous EDIT block. I think too, it can be simplify logger created without builder approach. I will create a static method for all main class (ReactiveLogger, Coroutin(K)Logger) and I will set to deprecated builder mechanism. I have seen I can simplify code.

**Comment by Michal-Kucera** [comment]
Hey!

I'm sorry, I didn't make myself clear in first, the delay was not in the code, but on my side, I wanted to test `3.0.0-RC1` release way sooner, though, my priorities were shifted back then :)

In relation to my last EDIT: for some reason `userId` was propagated to logs where we do not use `CoroutineKLogger` at all, to be more specific, you may see in the [aforelinked screenshot](
![](https://user-images.githubusercontent.com/46457233/188990410-fac5cba5-c3d4-4f02-ac28-cd7e57542f46.png)
) logs produced by `io.r2dbc.postgresql.QUERY` logger.

Unfortunately, I wasn't able to reproduce this, must had been some weird stuff going on in my setup, I have no better explanation for the moment.

Regarding to simplifying the usage of `CoroutineKLogger` and other loggers of yours, I agree, if possible, hide the implementation details might be the way to go.

**Comment by Numichi** [comment]
I plan, can work on it today and Sunday in my free time to release RC2. In parallel, I will have to correct students' exams of DevOps Bootcamp at the weekend.

**Comment by Numichi** [comment]
Now, you are going to hate me. :) I've decided that if we already make a major version now, I won't set it to deprecated, so I removed the builder mechanism because I have to maintain it for a long time. But it can be configured by the parameters like the previous builder.

I have released RC2. I just forgot to add another support method, like the `String` or `Class<*>` logger name, I will appear this in RC3 this weekend.

**Comment by Numichi** [comment]
Released RC3.
- `CoroutineKLogger.getLogger(...)`
- `CoroutineLogger.getLogger(...)`
- `ReactorKLogger.getLogger(...)`
- `ReactorLogger.getLogger(...)`

**Comment by Michal-Kucera** [comment]
Works well, thanks a lot!

**Comment by Numichi** [comment]
fyi: https://github.com/Numichi/reactive-logger/issues/12
